from . import articulo
from . import cantidad
from . import componente
from . import compramanufactura
from . import costoampliado
from . import costounitario
from . import departamento
from . import factorperdida
from . import fichatecnica
from . import secuencia
from . import temporada
from . import marca
from . import correlativo
from . import categoria
from . import subcategoria
from . import color
from . import talla
from . import numeracion
from . import copiaficha
from . import modelo
