from . import articulo
from . import cantidad
from . import componente
from . import compramanufactura
from . import costoampliado
from . import costounitario
from . import departamento
from . import factorperdida
from . import fichatecnica
from . import secuencia
from . import temporada
from . import copia_ficha_tecnica_wizard
